# Generated by Django 4.0.6 on 2022-07-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djbooks', '0005_alter_userslink_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userslink',
            name='links',
            field=models.CharField(max_length=200),
        ),
    ]
