# Generated by Django 4.0.6 on 2022-07-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djbooks', '0006_alter_userslink_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userslink',
            name='links',
        ),
        migrations.AddField(
            model_name='userslink',
            name='url',
            field=models.URLField(default='http//:'),
        ),
    ]
